version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3

jobs:
  test:
    docker:
      - image: cimg/node:16.19.0-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run:
          name: Install Node Modules
          command: npm install
      - run:
          name: Execute ESlint Check
          command: npm run eslint-check
      - run:
          name: Test
          command: npm test wdio.conf.js
      - store_test_results:
          path: report
workflows:
  version: 2
  test:
    jobs:
      - test